import {describe,it,expect} from 'vitest';
import {FinancialCore,SimulatedCloudflareAdapter} from '../shared/core';
import {SimulationProvider} from '../shared/simulation';
import {runAgent} from '../shared/orchestrator';
import {type ToolCall,type ModelProvider} from '../shared/contracts';
const date='2026-10-08';
function lab(fail=false){const core=new FinancialCore(),adapter=new SimulatedCloudflareAdapter(core,fail),provider=new SimulationProvider();return {core,adapter,run:(m:string)=>runAgent(provider,adapter,m,date)};}
describe('financial core e orquestração',()=>{
 it('registra receita e despesa e consolida saldo',async()=>{const l=lab();expect((await l.run('Recebi 1200 de freelance hoje')).status).toBe('success');expect((await l.run('Gastei 50 em mercado hoje')).status).toBe('success');const t=await l.run('Qual meu saldo?');expect(t.response?.ok&&t.response.result).toEqual({balance:3650,currency:'BRL'});expect(l.core.snapshot().transactions).toHaveLength(2);});
 it('mantém precisão em centavos',async()=>{const l=lab();await l.run('Gastei 0,10 em teste hoje');await l.run('Gastei 0,20 em teste hoje');const t=await l.run('saldo');expect(t.message).toContain('2.499,70');});
 it('lista e filtra transações',async()=>{const l=lab();await l.run('Recebi 100 de venda hoje');await l.run('Gastei 30 em almoço hoje');const t=await l.run('listar despesas');expect(t.response?.ok&&(t.response.result as any).transactions).toHaveLength(1);expect(t.message).toContain('almoço');});
 it('lista vazia é explícita',async()=>expect((await lab().run('listar transações')).message).toContain('Nenhuma transação'));
 it.each(['Gastei 0 em mercado hoje','Gastei -50 em mercado hoje','Gastei 1,234 em mercado hoje','Gastei 50 em mercado 2026-02-30','Gastei 1000001 em mercado hoje'])('rejeita dados inválidos: %s',async m=>{const l=lab();expect((await l.run(m)).status).toBe('clarification');expect(l.core.snapshot().transactions).toHaveLength(0);});
 it.each(['Gastei em mercado hoje','Gastei 50 em mercado','Gastei 50 hoje','Gastei 50 ou 100 em mercado hoje','Recebi 100 e gastei 50 hoje','Gastei 50 no cartão hoje','Talvez gastei 50 em mercado hoje','Não gastei 50 em mercado hoje','Gastei 50 em mercado ontem'])('pede esclarecimento: %s',async m=>{const l=lab();const t=await l.run(m);expect(t.status).toBe('clarification');expect(t.response).toBeUndefined();expect(l.core.snapshot().transactions).toHaveLength(0);});
 it('aceita moeda brasileira e data explícita',async()=>{const l=lab();const t=await l.run('Recebi R$ 1.234,56 de salário 2026-10-08');expect(t.status).toBe('success');expect(l.core.snapshot().transactions[0].amount).toBe(1234.56);});
 it('rejeita ferramenta desconhecida e IDs fornecidos pelo modelo',async()=>{const l=lab();for(const call of [{name:'executar_sql',arguments:{sql:'DROP TABLE'}},{name:'consultar_saldo',arguments:{workspace_id:'outro'}},{name:'registrar_transacao',arguments:{type:'despesa',amount:10,description:'a',date,user_id:'x'}}]){const r=await l.adapter.execute({version:'1',requestId:crypto.randomUUID(),call:call as ToolCall});expect(r.ok).toBe(false);}expect(l.core.snapshot().transactions).toHaveLength(0);});
 it('falha não altera estado nem confirma sucesso',async()=>{const l=lab(true);const t=await l.run('Gastei 50 em mercado hoje');expect(t.status).toBe('error');expect(t.message).not.toMatch(/registrada:/);expect(t.response?.ok).toBe(false);expect(l.core.snapshot().transactions).toHaveLength(0);});
 it('erro lançado pelo executor nunca confirma sucesso',async()=>{const t=await runAgent(new SimulationProvider(),{execute:async()=>{throw new Error('offline');}},'Gastei 50 em mercado hoje',date);expect(t.status).toBe('error');expect(t.message).not.toMatch(/registrada:/);});
 it('não confirma retorno sem correlação ou malformado',async()=>{const t=await runAgent(new SimulationProvider(),{execute:async()=>({requestId:'errado',ok:true,result:{}})},'Gastei 50 em mercado hoje',date);expect(t.status).toBe('error');});
 it('interpretação inválida não executa ferramentas',async()=>{let calls=0;const p={mode:'real',interpret:async()=>({intent:'x',call:{name:'sql',arguments:{}}})} as unknown as ModelProvider;const t=await runAgent(p,{execute:async()=>{calls++;throw new Error();}},'x',date);expect(calls).toBe(0);expect(t.status).toBe('error');});
 it('requisição idempotente registra uma única vez e bloqueia conflito',async()=>{const l=lab(),requestId=crypto.randomUUID();const request={version:'1' as const,requestId,call:{name:'registrar_transacao' as const,arguments:{type:'despesa' as const,amount:20,description:'teste',date}}};expect(await l.adapter.execute(request)).toEqual(await l.adapter.execute(request));expect(l.core.snapshot().transactions).toHaveLength(1);expect((await l.adapter.execute({...request,call:{...request.call,arguments:{...request.call.arguments,amount:30}}})).ok).toBe(false);});
 it('sessões são independentes',async()=>{const a=lab(),b=lab();await a.run('Gastei 50 em mercado hoje');expect(b.core.snapshot().transactions).toHaveLength(0);});
 it('snapshot não permite mutação externa',()=>{const l=lab();l.core.snapshot().initialBalanceCents=0;expect(l.core.snapshot().initialBalanceCents).toBe(250000);});
});
