import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {FinancialCore,SimulatedCloudflareAdapter,balanceCents} from '../shared/core';
import {SimulationProvider} from '../shared/simulation';
import {runAgent} from '../shared/orchestrator';
import {stateSchema,brl,todayBR,type Trace} from '../shared/contracts';
import './style.css';
const KEY='pulse-lab-session-v1';
function loadCore() { try { return new FinancialCore(stateSchema.parse(JSON.parse(sessionStorage.getItem(KEY)||'null'))); } catch { return new FinancialCore(); } }
const examples=['Qual meu saldo?','Gastei 50 em mercado hoje','Recebi 1200 de freelance hoje','Listar transações'];
function App(){
 const core=useRef(loadCore()),adapter=useRef(new SimulatedCloudflareAdapter(core.current)),provider=useRef(new SimulationProvider());
 const [messages,setMessages]=useState<{role:'user'|'assistant';text:string;trace?:Trace}[]>([{role:'assistant',text:'Olá! Sou o Pulse em modo simulação. Você começa com R$ 2.500 fictícios. Registre uma receita ou despesa e acompanhe a execução no Inspector.'}]);
 const [input,setInput]=useState(''),[busy,setBusy]=useState(false),[trace,setTrace]=useState<Trace>(),[revision,setRevision]=useState(0),[fail,setFail]=useState(false),[notice,setNotice]=useState(''),[showMode,setShowMode]=useState(false);
 const end=useRef<HTMLDivElement>(null),pending=useRef(false);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'});},[messages,busy]);
 const state=core.current.snapshot();void revision;
 async function send(text=input){
  if(pending.current||!text.trim()) return;pending.current=true;setBusy(true);setInput('');setNotice('');
  setMessages(prev=>[...prev,{role:'user',text:text.trim()}]);
  try { await new Promise(resolve=>setTimeout(resolve,180)); const result=await runAgent(provider.current,fail?new SimulatedCloudflareAdapter(core.current,true):adapter.current,text,todayBR());setFail(false);setTrace(result);setMessages(prev=>[...prev,{role:'assistant',text:result.message,trace:result}]);setRevision(v=>v+1);try{sessionStorage.setItem(KEY,JSON.stringify(core.current.snapshot()));}catch{setNotice('Armazenamento indisponível. A sessão continua em memória.');} }
  catch {setNotice('Falha inesperada. Consulte o saldo antes de repetir o lançamento.');}
  finally {pending.current=false;setBusy(false);}
 }
 function reset(){if(!confirm('Apagar os dados fictícios e o histórico desta sessão?'))return;core.current=new FinancialCore();adapter.current=new SimulatedCloudflareAdapter(core.current);try{sessionStorage.removeItem(KEY);}catch{}setMessages([{role:'assistant',text:'Sessão reiniciada. Saldo fictício de R$ 2.500,00.'}]);setTrace(undefined);setRevision(v=>v+1);setFail(false);}
 const status=trace?.status==='success'?'Executado':trace?.status==='error'?'Falha':trace?.status==='clarification'?'Precisa esclarecer':'Aguardando comando';
 return <div className="app"><aside className="rail"><div className="brand-symbol">p<span>•</span></div><div className="rail-active" title="Laboratório">⌘</div><div className="rail-footer">v1</div></aside><main><header><div className="brand"><strong>pulse<span> AI Lab</span></strong><small>AMBIENTE DE DESENVOLVIMENTO</small></div><button className="mode" onClick={()=>setShowMode(!showMode)}><span className="dot"/>Modo simulação <span>⌄</span></button></header>{showMode&&<div className="mode-details"><strong>Simulação ativa · zero tokens</strong><p>Interpretação determinística e dados fictícios. IA real: bloqueada. O conector de provedor está preparado no servidor, mas exige credenciais e autorização antes de ser conectado.</p></div>}
 <section className="intro"><div><div className="eyebrow">WORKSPACE / AGENT PLAYGROUND</div><h1>Uma conversa. Cada execução à vista.</h1><p>Teste comandos financeiros e acompanhe o caminho até o resultado.</p></div><button className="secondary" disabled={busy} onClick={reset}>↺ Nova sessão</button></section>
 <section className="stats"><div><span>SALDO FICTÍCIO</span><strong data-testid="balance">{brl(balanceCents(state)/100)}</strong><small>Consolidado nesta sessão</small></div><div><span>TRANSAÇÕES</span><strong>{state.transactions.length.toString().padStart(2,'0')}</strong><small>Dados de demonstração</small></div><div><span>AMBIENTE</span><strong className="safe">Isolado <i>↗</i></strong><small>Sem conexão com produção</small></div></section>
 <section className="workspace"><div className="chat panel"><div className="panel-head"><div><h2><span className="icon">✧</span> Conversa com o Pulse</h2><p>Explore, registre e consulte.</p></div><span className="pill">SIMULAÇÃO</span></div><div className="messages" aria-live="polite">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}><div className="avatar">{m.role==='assistant'?'✧':'M'}</div><div className="bubble"><small>{m.role==='assistant'?'PULSE AI':'VOCÊ'}</small><p>{m.text}</p>{m.trace&&<button className={`trace-link ${m.trace.status}`} onClick={()=>setTrace(m.trace)}>↗ {m.trace.status==='success'?'Execução concluída':m.trace.status==='error'?'Ver falha':'Ver esclarecimento'} · {m.trace.durationMs} ms</button>}</div></div>)}{busy&&<div className="loading">Interpretando comando e validando ferramenta…</div>}<div ref={end}/></div><div className="composer"><div className="examples">{examples.map(e=><button disabled={busy} key={e} onClick={()=>void send(e)}>{e}</button>)}</div><form onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="message">Sua mensagem</label><textarea id="message" value={input} maxLength={2000} disabled={busy} onChange={e=>setInput(e.target.value)} placeholder="Ex.: gastei 50 em mercado hoje" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}}/><button className="send" disabled={busy||!input.trim()} aria-label="Enviar mensagem">↑</button></form><div className="composer-note"><span>✧ Dados fictícios. Nenhum dinheiro é movimentado.</span><span>Enter para enviar</span></div>{notice&&<p role="alert" className="notice">{notice}</p>}</div></div>
 <div className="inspector panel"><div className="panel-head"><div><h2><span className="icon">⌘</span> Inspector</h2><p>O que aconteceu nesta execução.</p></div><span className="live"><span className="dot"/>Ao vivo</span></div><div className="inspector-body"><div className={`execution-status ${trace?.status||''}`}><span className="dot"/>{status}<span>{trace?`${trace.durationMs} ms`:'—'}</span></div><div className="field"><label>01 / INTENÇÃO IDENTIFICADA</label><strong>{trace?.intent||'Envie seu primeiro comando'}</strong></div><div className="field"><label>02 / FERRAMENTA ESCOLHIDA</label><code>{trace?.call?.name||'Nenhuma ferramenta solicitada'}</code></div><div className="field"><label>03 / ARGUMENTOS ENVIADOS</label><pre>{trace?.call?JSON.stringify(trace.call.arguments,null,2):'// Aguardando uma chamada'}</pre></div><div className="field"><label>04 / RESULTADO RETORNADO</label><pre className={trace?.status==='error'?'error-text':''}>{trace?.response?JSON.stringify(trace.response,null,2):trace?.status==='clarification'?'// Sem execução: esclarecimento necessário':'// Nenhum resultado ainda'}</pre></div>{trace&&<div className="request-id">REQUEST ID <code>{trace.requestId}</code></div>}<div className="flow"><span>Pulse AI</span><b>→</b><span>Worker simulado</span><b>→</b><span>Core</span></div><label className="failure"><input type="checkbox" checked={fail} disabled={busy} onChange={e=>setFail(e.target.checked)}/>Simular falha na próxima execução</label><p className="inspector-note">Apenas dados operacionais. O Inspector não mostra raciocínio privado do modelo.</p></div></div></section><footer><span><span className="dot"/>Laboratório pronto</span><span>Pulse AI → Cloudflare → Financial Core <b>·</b> Supabase desconectado</span></footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
